#=========================================================================#
# devd.conf
#=========================================================================#


#=========================================================================#
# Handle the Alfa Card being plugged in
#=========================================================================#

notify 100 {
    match "system"      "IFNET";
    match "subsystem"   "wlan0";  # Use your wlan interface name
    match "type"        "ATTACH";
    action "ifconfig lagg0 laggport wlan0";
};


#=========================================================================#
# Clean up if the Alfa Card is unplugged
#=========================================================================#

notify 100 {
    match "system"      "IFNET";
    match "subsystem"   "wlan0";
    match "type"        "DETACH";
    action "ifconfig lagg0 -laggport wlan0";
};
